# Generated by Django 4.1.7 on 2023-03-18 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameStudentOne', models.CharField(max_length=255)),
                ('nameStudentTwo', models.CharField(blank=True, max_length=255)),
                ('nameAdvisorOne', models.CharField(max_length=255)),
                ('nameAdvisorTwo', models.CharField(blank=True, max_length=255)),
                ('nameSchool', models.CharField(max_length=255)),
                ('nameArticle', models.CharField(max_length=255)),
                ('article', models.FileField(upload_to='media/articles/')),
            ],
        ),
    ]
