# Generated by Django 4.1.7 on 2023-03-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soscorais', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='article',
            field=models.FileField(upload_to='articles/'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='nameAdvisorOne',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='registration',
            name='nameAdvisorTwo',
            field=models.CharField(blank=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='registration',
            name='nameArticle',
            field=models.CharField(max_length=75, unique=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='nameSchool',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='registration',
            name='nameStudentOne',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='registration',
            name='nameStudentTwo',
            field=models.CharField(blank=True, max_length=75),
        ),
    ]
