# Generated by Django 4.1.7 on 2023-03-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soscorais', '0002_alter_registration_article_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='emailHead',
            field=models.EmailField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='phoneNumberHead',
            field=models.CharField(default=1, max_length=11),
            preserve_default=False,
        ),
    ]
