# Generated by Django 4.1.7 on 2023-03-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soscorais', '0003_registration_emailhead_registration_phonenumberhead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='nameArticle',
            field=models.CharField(max_length=90, unique=True),
        ),
    ]
