# Generated by Django 4.1.7 on 2023-03-21 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soscorais', '0004_alter_registration_namearticle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='phoneNumberHead',
            field=models.CharField(max_length=20),
        ),
    ]
